let state, tables, current='holdings', dirty=false, actor='USER', pending=null;
const $=id=>document.getElementById(id);
const names={theses:'投資仮説',research:'調査課題',exposures:'構成内訳',plans:'比較案',plan_items:'比較明細',checks:'点検記録',holdings:'保有台帳',targets:'目標配分',analyses:'分析ノート',sources:'出典',news:'ニュース・PTS',decisions:'判断履歴'};
const labels={holdingId:'保有ID',reason:'保有理由',expectation:'期待する変化',metric:'確認指標',baseline:'前回値・時点',latest:'最新値・時点',threshold:'判定基準',change:'前回からの変化',reviewOn:'次回確認日',reviewedAt:'確認日時',thesisStatus:'仮説状態',question:'調査課題',decisionLink:'判断への関係',impact:'判断影響1〜5',uncertainty:'不確実性1〜5',urgency:'緊急度1〜5',effort:'負担1〜5',dueOn:'調査期限',researchStatus:'調査状態',nextAction:'次の調査',result:'判明したこと',dimension:'内訳分類',component:'構成項目',mode:'案の種別',baselineHash:'比較元ハッシュ',additionalCashJpy:'追加資金・円',feesJpy:'費用仮定・円',taxJpy:'税仮定・円',benefit:'期待効果',risk:'リスク',assumptions:'前提',invalidation:'見直す条件',planId:'比較案ID',targetValueJpy:'提案評価額・円',subject:'点検対象',checkedAt:'確認日時',checkStatus:'点検状態',detail:'確認内容',id:'固定ID',scope:'区分',bucket:'枠',code:'コード',name:'銘柄・商品名',account:'口座区分',currency:'通貨',quantity:'数量',avgCost:'平均取得単価',costBasisJpy:'取得原価・円',price:'価格',fx:'円換算FX',priceAsOf:'価格基準日時',marketValueJpy:'報告評価額・円',pnlJpy:'報告損益・円',tags:'リスクタグ',quality:'品質',sourceId:'出典ID',note:'備考',role:'役割',weight:'目標比率・小数',status:'状態',title:'タイトル',asOf:'基準日時',conclusion:'結論',rationale:'根拠',counterCase:'反対仮説',falsifier:'撤回条件',nextReview:'次回確認',kind:'出典種別',uri:'URL・資料名',publishedAt:'公表日時',retrievedAt:'取得日時',dataAsOf:'データ基準日時',confidence:'確度',pts:'PTS価格',ptsAsOf:'PTS時刻',ptsVolume:'PTS出来高',close:'日中終値',closeAsOf:'終値基準日時',stars:'重要度・星1〜5',direction:'影響の方向',summary:'内容',reviewAction:'確認すべき点',proposal:'提案',approvalEvidence:'承認根拠',executionEvidence:'実行根拠'};
const hints={theses:'保有理由・確認指標・撤回条件を固定IDで追跡します。',research:'保存すると優先順位を再計算します。各点数は1〜5、未採点は空欄。',exposures:'比率は小数（20%は0.2）。未取得部分を100%へ補正しません。',plans:'現状維持・追加資金・組替えを金額で比較。0円も明示入力。保存で再計算。',plan_items:'保有IDを指定して提案評価額を入力。未記載の保有は維持。新候補は保有IDを空欄にしてコード・名前・枠を入力。',checks:'実際に確認した日時と内容を記録します。設定済みと動作確認済みは別です。',holdings:'空欄は不明値。評価額・損益の再計算は上の保存済みダッシュボードで確認できます。',targets:'既存の目標配分は未移行です。推定で作らず、承認された配分だけをACTIVEにします。',analyses:'AIの根拠・反対仮説・撤回条件を、あなたも直接編集できます。',sources:'重要な数値と判断は、この出典IDに紐づけます。',news:'星は材料の重要度です。POSITIVE / NEGATIVE 等の方向と確度を別に記録します。',decisions:'履歴は追記のみ。訂正は新しいIDで追加してください。'};
const long=new Set(['reason','expectation','change','question','decisionLink','nextAction','result','benefit','risk','assumptions','invalidation','detail','note','conclusion','rationale','counterCase','falsifier','summary','reviewAction','proposal','approvalEvidence','executionEvidence']);
const enums={thesisStatus:['UNREVIEWED','SUPPORTED','WATCH','CHALLENGED'],researchStatus:['OPEN','IN_PROGRESS','DONE','BLOCKED'],dimension:['ISSUER','SECTOR','CURRENCY'],mode:['HOLD','ADD','REBALANCE'],subject:['HOLDINGS','NOTIFICATION','EXTERNAL_BACKUP'],checkStatus:['UNKNOWN','CONFIRMED','FAILED'],scope:['taxable','ideco'],bucket:['目標構成','保留枠','守備枠','年金コア'],currency:['JPY','USD'],quality:['UNKNOWN','EST','FACT'],direction:['UNKNOWN','POSITIVE','NEGATIVE','MIXED','NEUTRAL'],confidence:['UNVERIFIED','SINGLE_SOURCE','CORROBORATED','CONFLICTED'],kind:['USER_PRIMARY','REGULATOR_PRIMARY','ISSUER_PRIMARY','MARKET_DATA','SECONDARY','ESTIMATE']};
const displayValue={taxable:'課税口座',ideco:'iDeCo',UNKNOWN:'不明',EST:'推定を含む',FACT:'元資料で確認',PROPOSED:'提案',APPROVED:'承認済み',EXECUTED:'実行確認済み',ACTIVE:'有効',INACTIVE:'無効',POSITIVE:'好影響',NEGATIVE:'悪影響',MIXED:'混在',NEUTRAL:'中立',UNVERIFIED:'未検証',SINGLE_SOURCE:'単一出典',CORROBORATED:'照合済み',CONFLICTED:'矛盾あり',USER_PRIMARY:'ユーザー資料',REGULATOR_PRIMARY:'法定開示',ISSUER_PRIMARY:'発行体資料',MARKET_DATA:'市場データ',SECONDARY:'二次情報',ESTIMATE:'推定'};
const money=v=>v===null?'未算定':new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(v);
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function message(text=''){$('message').textContent=text;}
function modified(){dirty=true;$('saveState').textContent='未保存の編集あり · 上部は保存済みの値';}
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':state.token},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw Error(data.error||'読込失敗');return data;}
function action(fn){return async(...args)=>{try{await fn(...args);}catch(e){message(e.message);}};}
async function load(){state=await api('/api/state');tables=structuredClone(state.tables);dirty=false;actor='USER';pending=null;render();message();}
function dashboard(){const s=state.summary;$('cards').replaceChildren();
 [['登録資産の参考小計',money(s.subtotal),s.missing?`評価額未算定 ${s.missing}件。構成比を表示しません。`:'時点混在・現金などの網羅性は未確認'],['課税口座',money(s.taxable),'年金コアと分離して表示'],['年金コア / iDeCo',money(s.ideco),'保有方針：スイッチングなし'],['算定できた円建て損益',money(s.pnlSubtotal),`損益未確定 ${s.pnlMissing}件。総損益ではありません`]].forEach(([title,value,note])=>{const n=el('article',undefined,'card');n.append(el('small',title),el('strong',value),el('p',note));$('cards').append(n);});
 $('allocation').replaceChildren();const groups={};s.rows.forEach(r=>{if(r.value!==null)groups[r.bucket]=(groups[r.bucket]||0)+r.value;});Object.entries(groups).sort((a,b)=>b[1]-a[1]).forEach(([label,value])=>{const row=el('div',undefined,'barrow'),track=el('div',undefined,'track'),fill=el('div',undefined,'fill');fill.style.width=s.missing?'0%':(s.subtotal?100*value/s.subtotal:0)+'%';track.append(fill);row.append(el('span',label),track,el('span',money(value)));$('allocation').append(row);});
 $('issues').replaceChildren(...s.issues.map(t=>el('li',t)));$('issues').append(el('li','価格・評価基準日：'+s.dates.join(' / ')),el('li','銘柄・価格は持込CSVの記載。現在値・企業名の外部照合は未実施です。'));
 $('saveState').textContent='Mac保存済み · '+new Date(state.meta.savedAt).toLocaleString('ja-JP');
 $('backupInfo').textContent='保存ごとに全CSVと変更履歴をZIP保存。保存先：'+state.backupPath;
 $('history').replaceChildren();state.history.slice(0,30).forEach(h=>{const row=el('div');row.append(el('span',new Date(h.savedAt).toLocaleString('ja-JP')+' · '+h.reason));const b=el('button','この版を確認');b.onclick=action(async()=>{if(dirty&&!confirm('未保存の編集を破棄して復元候補を読み込みますか？'))return;const r=await api('/api/restore-preview',{target:h.version});tables=r.tables;actor='RESTORE';$('reason').value='過去版から復元: '+h.version;modified();grid();await review();});row.append(b);$('history').append(row);});
}
function render(){dashboard();renderInsights();$('tabs').replaceChildren();for(const key of Object.keys(names)){const b=el('button',names[key],key===current?'active':'');b.onclick=()=>{current=key;$('search').value='';grid();[...$('tabs').children].forEach((n,i)=>n.className=Object.keys(names)[i]===key?'active':'');};$('tabs').append(b);}grid();}
function grid(){const columns=current==='holdings'?'code name bucket quantity avgCost price currency fx priceAsOf marketValueJpy costBasisJpy pnlJpy quality tags note scope account sourceId id'.split(' '):state.schemas[current];$('tableTitle').textContent=names[current];$('tableHint').textContent=hints[current];const tr=el('tr');columns.forEach(c=>tr.append(el('th',labels[c]||c)));tr.append(el('th','操作'));$('head').replaceChildren(tr);$('body').replaceChildren();const filter=$('search').value.toLowerCase();
 tables[current].forEach((row,index)=>{if(filter&&!Object.values(row).join(' ').toLowerCase().includes(filter))return;const tr=el('tr');columns.forEach(c=>{const td=el('td');let choices=enums[c];if(c==='status')choices=current==='targets'?['PROPOSED','ACTIVE','INACTIVE']:['analyses','plans'].includes(current)?['PROPOSED','APPROVED']:['PROPOSED','APPROVED','EXECUTED'];let input;if(choices){input=el('select');choices.forEach(v=>{const o=el('option',displayValue[v]||v);o.value=v;input.append(o);});}else input=el(long.has(c)||c==='name'?'textarea':'input');input.value=row[c];input.title=row[c];input.setAttribute('aria-label',names[current]+' '+(labels[c]||c)+' '+row.id);if((c==='id'&&state.tables[current].some(r=>r.id===row.id))||(current==='decisions'&&state.tables.decisions.some(r=>r.id===row.id)))input.disabled=true;input.oninput=()=>{row[c]=input.value;modified();};td.append(input);tr.append(td);});const td=el('td'),b=el('button','削除','delete');b.disabled=current==='decisions'&&state.tables.decisions.some(r=>r.id===row.id);b.onclick=()=>{tables[current].splice(index,1);modified();grid();};td.append(b);tr.append(td);$('body').append(tr);});
}
async function review(){const result=await api('/api/preview',{version:state.version,tables});if(!result.changes.length){message('変更はありません');return;}pending=structuredClone(tables);$('diff').replaceChildren();result.changes.forEach(c=>{const box=el('div');box.append(el('h3',names[c.table]+' / '+c.id+(c.before?'':' · 追加')+(c.after?'':' · 削除')));const lines=[];for(const key of state.schemas[c.table]){const a=c.before?.[key]??'（行なし）',b=c.after?.[key]??'（行なし）';if(a!==b)lines.push((labels[key]||key)+': '+(a||'空欄')+' → '+(b||'空欄'));}box.append(el('pre',lines.join('\n')));$('diff').append(box);});$('diff').append(el('p','保存後の登録評価額の参考小計：'+money(result.summary.subtotal)+' ／ 損益未確定 '+result.summary.pnlMissing+'件'));$('dialog').showModal();}
function download(name,value,type='application/json'){const blob=new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type});const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('review').onclick=action(review);$('cancel').onclick=()=>{$('dialog').close();pending=null;};
$('commit').onclick=action(async()=>{if(!$('reason').value.trim()){message('変更理由を入力してください');$('dialog').close();return;}$('commit').disabled=true;try{await api('/api/commit',{version:state.version,tables:pending,actor,reason:$('reason').value});$('dialog').close();$('reason').value='';await load();message('保存・読み戻し・バックアップの検証が完了しました。');}finally{$('commit').disabled=false;}});
$('refresh').onclick=action(async()=>{if(dirty&&!confirm('未保存の編集を破棄して最新版を読み込みますか？'))return;await load();});
$('search').oninput=grid;
$('add').onclick=()=>{const row=Object.fromEntries(state.schemas[current].map(k=>[k,'']));row.id=current.slice(0,3)+'_'+crypto.randomUUID().slice(0,8);if(current==='holdings')Object.assign(row,{scope:'taxable',bucket:'保留枠',currency:'JPY',fx:'1',quality:'UNKNOWN'});if(current==='news')Object.assign(row,{direction:'UNKNOWN',confidence:'UNVERIFIED'});if(current==='sources')Object.assign(row,{kind:'USER_PRIMARY',confidence:'UNVERIFIED'});if(current==='theses')row.thesisStatus='UNREVIEWED';if(current==='research')row.researchStatus='OPEN';if(current==='exposures')Object.assign(row,{dimension:'ISSUER',quality:'UNKNOWN'});if(current==='checks')Object.assign(row,{subject:'HOLDINGS',checkStatus:'UNKNOWN'});if(current==='plans')Object.assign(row,{mode:'HOLD',baselineHash:state.insights.comparison.baselineHash});if('status'in row)row.status='PROPOSED';tables[current].push(row);modified();grid();};
$('csvExport').onclick=action(async()=>{if(dirty)message('保存済みのCSVを出力します。未保存の編集は含みません。');const r=await fetch('/api/csv?table='+current);if(!r.ok)throw Error('CSV出力失敗');download(current+'.csv',await r.text(),'text/csv;charset=utf-8');});
$('csvImport').onchange=action(async e=>{const file=e.target.files[0];if(!file)return;const r=await api('/api/import-csv',{table:current,csv:await file.text()});tables[current]=r.rows;actor='USER';modified();grid();message('CSVを編集候補に取り込みました。差分確認後に保存してください。');e.target.value='';});
$('jsonExport').onclick=action(async()=>{download('investingOS-ai-context.json',await api('/api/export'));message('保存済みデータを出力しました。利用するAIサービスに渡す内容を確認してください。');});
$('jsonImport').onchange=action(async e=>{const file=e.target.files[0];if(!file)return;const candidate=JSON.parse(await file.text());await api('/api/preview',candidate);if(candidate.version!==state.version)throw Error('CONFLICT: 画面も最新版を読み直してください');if(dirty&&!confirm('現在の未保存編集を更新案に置き換えますか？'))return;tables=candidate.tables;actor='AI';$('reason').value=candidate.reason||'AIの更新案を確認';modified();grid();await review();e.target.value='';});
$('backup').onclick=action(async()=>{const result=await api('/api/backup',{});message('バックアップを検証しました：'+result.path);});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
setInterval(async()=>{try{const remote=await api('/api/state');if(remote.version!==state.version){if(dirty)message('別の編集が保存されました。未保存データを退避し、最新版と統合してください。');else await load();}else if(insightTab==='health'){state.insights.health=remote.insights.health;renderInsights();}}catch(e){$('saveState').textContent='接続を確認してください · '+e.message;}},15000);
load().catch(e=>message(e.message));
