let insightTab='theses';
const insightNames={theses:'① 投資仮説',research:'② 調査の優先順位',risk:'③ 重複・ストレス',compare:'④ 提案比較',health:'⑥ 稼働状況'};
const captions={SUPPORTED:'仮説を支持',WATCH:'要注視',CHALLENGED:'仮説に反する',UNREVIEWED:'未確認',OPEN:'未着手',IN_PROGRESS:'調査中',DONE:'完了',BLOCKED:'取得待ち',HOLD:'現状維持',ADD:'追加資金で調整',REBALANCE:'一部組替え',ISSUER:'構成銘柄',SECTOR:'業種',CURRENCY:'通貨',CONFIRMED:'確認済み',FAILED:'失敗',UNKNOWN:'不明',VERIFIED:'検証済み',MISSING:'未検出',SUCCESS:'成功',PARTIAL:'一部成功',SKIPPED:'休場等で省略',UNVERIFIED:'未検証',RECORDED:'日付記録あり',REVIEW:'要更新',HOLDINGS:'保有確認',NOTIFICATION:'通知到達',EXTERNAL_BACKUP:'別媒体バックアップ'};
Object.assign(displayValue,captions);
function field(row,key,title,multiline=false){const label=el('label',title,'insight-field');const input=el(multiline?'textarea':'input');input.value=row[key];input.setAttribute('aria-label',title+' '+row.id);input.oninput=()=>{row[key]=input.value;modified();};label.append(input);return label;}
function choice(row,key,title,values){const label=el('label',title,'insight-field'),input=el('select');values.forEach(v=>{const o=el('option',captions[v]||displayValue[v]||v);o.value=v;input.append(o);});input.value=row[key];input.setAttribute('aria-label',title+' '+row.id);input.onchange=()=>{row[key]=input.value;modified();};label.append(input);return label;}
function simpleTable(headers,rows){const wrap=el('div',undefined,'mini-grid'),table=el('table'),head=el('tr');headers.forEach(h=>head.append(el('th',h)));table.append(head);rows.forEach(values=>{const tr=el('tr');values.forEach(v=>tr.append(el('td',v)));table.append(tr);});wrap.append(table);return wrap;}
function pct(v){return v===null||v===undefined?'未算定':(v*100).toFixed(1)+'%';}
function pickTable(key){current=key;$('search').value='';grid();[...$('tabs').children].forEach((n,i)=>n.className=Object.keys(names)[i]===key?'active':'');$('tableTitle').scrollIntoView({behavior:'smooth',block:'start'});}
function editButton(key,label='明細を編集'){const b=el('button',label);b.onclick=()=>pickTable(key);return b;}
function renderInsights(){if(!state.insights)return;$('insightNav').replaceChildren();Object.entries(insightNames).forEach(([key,name])=>{const b=el('button',name,key===insightTab?'active':'');b.onclick=()=>{insightTab=key;renderInsights();};$('insightNav').append(b);});const host=$('insightContent');host.replaceChildren();
 if(insightTab==='theses')renderTheses(host);
 if(insightTab==='research')renderResearch(host);
 if(insightTab==='risk')renderRisk(host);
 if(insightTab==='compare')renderComparison(host);
 if(insightTab==='health')renderHealth(host);
}
const cat=()=>state.catalog||{reasons:[],expectations:[],metrics:[],falsifiers:[]};
function tagCode(v){const m=/^#([A-Z_]+)\b/.exec((v||'').trim());return m?m[1]:'';}
function tagBody(v){const t=(v||'').trim();if(!t.startsWith('#'))return t;return t.split('\n').slice(1).join('\n').trim();}
function picker(row,key,title,options,placeholder){const wrap=el('div',undefined,'insight-field');wrap.append(el('span',title,'field-title'));const sel=el('select');const blank=el('option','選択してください（任意）');blank.value='';sel.append(blank);options.forEach(o=>{const x=el('option',o.label);x.value=o.code;sel.append(x);});sel.value=tagCode(row[key]);sel.setAttribute('aria-label',title+'の分類 '+row.id);const area=el('textarea');area.value=tagBody(row[key]);area.placeholder=placeholder||'自由記述。選択肢に無いこと、具体的な事情はここへ。';area.setAttribute('aria-label',title+'の自由記述 '+row.id);const sync=()=>{const opt=options.find(o=>o.code===sel.value);const head=opt?('#'+opt.code+' '+opt.label):'';const body=area.value.trim();row[key]=(head+(body?'\n'+body:'')).trim();modified();};sel.onchange=sync;area.oninput=sync;wrap.append(sel,area);return wrap;}
function suggestField(row,key,title,options,placeholder){const wrap=el('div',undefined,'insight-field');wrap.append(el('span',title,'field-title'));const sel=el('select');const blank=el('option','よく使う項目から選ぶ');blank.value='';sel.append(blank);options.forEach(o=>{const x=el('option',o.code+(o.unit?'（'+o.unit+'）':''));x.value=o.code;sel.append(x);});const input=el('input');input.value=row[key];input.placeholder=placeholder||'自由入力できます';input.setAttribute('aria-label',title+' '+row.id);const hint=el('p','','muted');sel.onchange=()=>{const o=options.find(o=>o.code===sel.value);if(!o)return;input.value=o.code;hint.textContent=o.note||'';row[key]=input.value;modified();};input.oninput=()=>{row[key]=input.value;modified();};wrap.append(sel,input,hint);return wrap;}
function ruleLine(t,value){const v=(value===''||value===null||value===undefined)?t.default:Number(value);if(t.kind==='stale')return '@stale '+t.metric+' '+Math.round(v)+'d : '+t.label;return '@falsify '+t.metric+' '+t.op+' '+v+' '+t.unit+' : '+t.label;}
function falsifierEditor(row){const wrap=el('div',undefined,'insight-field');wrap.append(el('span','撤回条件（選んで追加 → 自由に編集）','field-title'));const templates=cat().falsifiers;const line=el('div',undefined,'rule-builder');const sel=el('select');const blank=el('option','撤回条件を選ぶ');blank.value='';sel.append(blank);templates.forEach(t=>{const x=el('option',t.label);x.value=t.code;sel.append(x);});const num=el('input');num.type='number';num.step='any';num.placeholder='基準値';num.setAttribute('aria-label','撤回条件の基準値 '+row.id);const add=el('button','この条件を追加');add.type='button';const hint=el('p','テンプレを選ぶと基準値の意味が出ます。数値はあなたの基準に直してください。','muted');const area=el('textarea');area.value=row.falsifier;area.placeholder='@falsify 営業利益率 lt 10 % : 利益率が二桁を割る\n自由記述の条件もこの下に書けます（検証は数式行のみ）';area.setAttribute('aria-label','撤回条件 '+row.id);const count=el('p','','muted');const refresh=()=>{const n=(area.value.match(/^@(falsify|stale)\s/gm)||[]).length;count.textContent=n?('検証できる条件: '+n+'件'):'検証できる条件: 0件 — この状態では反証エンジンが「UNTESTABLE」と報告します。';};sel.onchange=()=>{const t=templates.find(t=>t.code===sel.value);if(!t){hint.textContent='';return;}num.value=t.default;hint.textContent=t.valueLabel;};add.onclick=()=>{const t=templates.find(t=>t.code===sel.value);if(!t){hint.textContent='先に撤回条件を選んでください。';return;}const text=ruleLine(t,num.value);area.value=(area.value.trim()?area.value.trim()+'\n':'')+text;row.falsifier=area.value;modified();refresh();};line.append(sel,num,add);wrap.append(line,hint,area,count);refresh();return wrap;}
function renderTheses(host){host.append(el('h2','保有理由と、考え直す条件'),el('p','未確認の仮説を事実として補完しません。ニュースが届いたら「前回からの変化」と出典を更新します。','muted'));const cards=el('div',undefined,'thesis-grid');const map=Object.fromEntries(tables.holdings.map(r=>[r.id,r]));tables.theses.forEach(row=>{const card=el('details',undefined,'thesis-card'),heading=el('summary',(map[row.holdingId]?.name||row.holdingId)+' · '+(captions[row.thesisStatus]||row.thesisStatus));card.append(heading);const fields=el('div',undefined,'form-grid');fields.append(choice(row,'thesisStatus','仮説の状態',['UNREVIEWED','SUPPORTED','WATCH','CHALLENGED']),field(row,'reviewOn','次回確認日'),picker(row,'reason','保有理由',cat().reasons,'なぜ持っているか。選択肢に無い事情をここへ。'),picker(row,'expectation','期待する変化',cat().expectations,'いつまでに何が起きれば仮説どおりか。'),suggestField(row,'metric','確認する指標',cat().metrics),field(row,'threshold','確認・撤回の基準'),field(row,'baseline','前回の値・時点'),field(row,'latest','最新の値・時点'),field(row,'change','前回からの変化',true),picker(row,'counterCase','反対仮説',cat().reasons,'この仮説が外れるとしたら何が起きている時か。'),falsifierEditor(row),field(row,'reviewedAt','最終確認日時'),field(row,'sourceId','出典ID'));card.append(fields);cards.append(card);});host.append(cards,editButton('theses','カードを追加・明細編集'));}
function renderResearch(host){host.append(el('h2','結論を左右する未確認事項から調べる'),el('p','順位は期限超過を先にし、判断影響×不確実性＋緊急度×2で並べます（各1〜5）。同点は負担の小さい順。成功確率や売買推奨点ではありません。表示は保存済みの値です。','muted'));const rows=state.insights.queue;host.append(simpleTable(['優先点','調査課題','判断への関係','期限','次の一手','状態'],rows.map(r=>[(r.overdue?'期限超過 · ':'')+(r.score??'未採点'),r.question,r.decisionLink,r.dueOn||'未指定',r.nextAction,captions[r.researchStatus]])));if(!rows.length)host.append(el('p','未完了の調査課題はありません。'));host.append(editButton('research','調査課題・採点を編集'));}
function renderRisk(host){const risk=state.insights.risk;host.append(el('h2','共通リスクを、商品をまたいで確認'),el('p','同じタグを持つ登録資産の重なりです。ETFの構成比や相関の推計ではありません。複数タグに該当するため合計100%にはなりません。','muted'),simpleTable(['リスクタグ','該当資産の参考小計','登録資産に対する参考比率'],risk.tags.map(([tag,value])=>[tag,money(value),pct(risk.denominator?value/risk.denominator:null)])));
 const dimensions=el('div',undefined,'thesis-grid');Object.entries(risk.dimensions).forEach(([key,d])=>{const box=el('article',undefined,'subpanel');box.append(el('h3',captions[key]+'の内訳'),el('p','取得済み内訳の集計範囲 '+pct(d.coverage)+' ／ 未割当の既知評価額 '+money(d.unmappedKnown),'muted'));if(d.components.length)box.append(simpleTable(['内訳','金額'],d.components.map(([k,v])=>[k,money(v)])),el('p','構成基準日：'+d.dates.join(' / ')+(d.hasEstimates?' · 推定を含む':''),'muted'));else box.append(el('p','構成情報が未登録です。名称から推定して埋めません。'));dimensions.append(box);});host.append(dimensions,editButton('exposures','構成銘柄・業種・通貨の内訳を登録'));
 const stress=el('article',undefined,'subpanel');stress.append(el('h3','仮定を置いたストレス試算'),el('p','すべての商品自体の価格変化率を適用します。USD建て行だけに追加のUSD/JPY変化率を乗算。円建て投信の内包為替や日次レバレッジの経路は別途未モデル化。予測・最大損失ではありません。','muted'));const fields=el('div',undefined,'actions');[['securityShock','商品価格変化率（%）','-20'],['fxShock','USD/JPY変化率（%）','-10']].forEach(([id,title,value])=>{const label=el('label',title);const input=el('input');input.type='number';input.id=id;input.value=value;input.min='-100';input.max='500';input.setAttribute('aria-label',title);label.append(input);fields.append(label);});const b=el('button','この仮定で試算','primary'),output=el('div');b.onclick=action(async()=>{const result=await api('/api/simulate',{version:state.version,pricePct:$('securityShock').value,fxPct:$('fxShock').value});output.replaceChildren(el('p','参考小計 '+money(result.before)+' → '+money(result.after)+' ／ 変化 '+money(result.after-result.before)+(result.missing?' · 未算定 '+result.missing+'件':'')),simpleTable(['商品','現在の参考評価額','仮定適用後','変化'],result.rows.map(r=>[r.name,money(r.before),money(r.after),money(r.change)])));});fields.append(b);stress.append(fields,output);host.append(stress);}
function renderComparison(host){const comparison=state.insights.comparison;host.append(el('h2','現状維持・追加資金・一部組替えを比較'),el('p',comparison.scope+' 費用・税はユーザー/AIが根拠付きで入力する仮定です。','muted'));const cards=el('div',undefined,'thesis-grid');comparison.results.forEach(p=>{const card=el('article',undefined,'subpanel');card.append(el('h3',p.title),el('p',captions[p.mode]+' · '+(displayValue[p.status]||p.status),'muted'));if(p.problems.length)card.append(...p.problems.map(t=>el('p',t,'attention')));if(p.warnings?.length)card.append(...p.warnings.map(t=>el('p',t,'attention')));if(p.positions){card.append(el('p','調整後の参考資産 '+money(p.netAssets)+' ／ 未配分資金 '+money(p.cash)),el('p','最大商品比率 '+pct(p.maxWeight)+' ／ 上位3商品 '+pct(p.top3Weight),'muted'),simpleTable(['対象','変更額','提案評価額','構成比'],p.positions.filter(r=>r.value||r.change).map(r=>[r.name,money(r.change),money(r.value),pct(r.weight)])));}card.append(el('p','期待効果：'+(p.benefit||'未入力')),el('p','リスク：'+(p.risk||'未入力')),el('p','前提：'+(p.assumptions||'未入力')),el('p','見直す条件：'+(p.invalidation||'未入力')));cards.append(card);});host.append(cards);const controls=el('div',undefined,'actions');controls.append(editButton('plans','比較案・追加資金・費用を編集'),editButton('plan_items','提案する金額配分を編集'));const add=el('button','比較案を追加');add.onclick=()=>{pickTable('plans');$('add').click();};controls.append(add);host.append(controls,el('p','比較元が古い場合、最新データで案を検討し直してから baselineHash を更新してください。最新ハッシュ：'+comparison.baselineHash,'muted'));}
function renderHealth(host){const h=state.insights.health;host.append(el('h2','データと監視の健康状態'),el('p','評価時刻：'+new Date(h.evaluatedAt).toLocaleString('ja-JP')+'。価格の7日超は確認を促す目安で、取引所営業日やリアルタイム取得の保証ではありません。','muted'));const cards=el('div',undefined,'thesis-grid');for(const [subject,label] of Object.entries({HOLDINGS:'保有の確認',NOTIFICATION:'通知の到達',EXTERNAL_BACKUP:'別媒体バックアップ'})){const r=h.confirmations[subject],card=el('article',undefined,'subpanel');card.append(el('h3',label),el('p',r?(captions[r.checkStatus]+' · '+(r.checkedAt||'日時不明')):'未確認'),el('p',r?.detail||'確認した日時と根拠が未登録です。','muted'));cards.append(card);}const backup=el('article',undefined,'subpanel');backup.append(el('h3','保存版のMacバックアップ'),el('p',captions[h.backup]||h.backup),el('p','現在の版とZIP内CSVのハッシュを照合。同じMac内のコピーです。','muted'));const monitor=el('article',undefined,'subpanel');monitor.append(el('h3','定期監視の実行'),el('p',captions[h.monitoring.status]||h.monitoring.status),el('p','最終試行：'+(h.monitoring.lastAttemptAt||'未記録')+' ／ 最終成功：'+(h.monitoring.lastSuccessAt||'未記録'),'muted'),el('p',h.monitoring.detail));cards.append(backup,monitor);host.append(cards,editButton('checks','保有・通知・別媒体の確認記録を追加'),simpleTable(['保有商品','価格・評価基準日','経過日数','状態'],h.prices.map(r=>[r.name,r.asOf||'未記録',r.ageDays===null?'不明':r.ageDays+'日',captions[r.status]])));}
